api_platform:
    title: 'BileMo'
    description: "Projet 7 du parcours Développeur d'application - PHP / Symfony d'OpenClassrooms : réalisation d'une API REST avec Symfony."
    version: '1.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    http_cache:
        invalidation:
            enabled: true
            varnish_urls: []
        max_age: 0
        shared_max_age: 3600
        vary: ['Content-Type', 'Authorization', 'Origin']
        public: true
    collection:
        pagination:
            items_per_page: 20
