api_platform:
    title: 'BileMo'
    description: "Projet 7 du parcours Développeur d'application - PHP / Symfony d'OpenClassrooms : réalisation d'une API REST avec symfony."
    version: '1.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
